### ISSUE TITLE
Crashing on switching feeds

### ISSUE THREAD

**Issue by thomasschuiki** [Lallassu/gorss#26]
Hi,

cannot say for sure what I did. But it just crashed after a few seconds "browsing".

GO VERSION
`go version go1.15.7 linux/amd64`

**GO ENV**
```
~ $ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tom/.cache/go-build"
GOENV="/home/tom/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/tom/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tom/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build016152857=/tmp/go-build -gno-record-gcc-switches"
```

**Error Message**
```
~ $ gorss
2021/01/24 14:14:28 main.go:89: Using config: /home/tom/.config/gorss/gorss.conf
2021/01/24 14:14:28 main.go:90: Using theme: /home/tom/.config/gorss/themes/default.theme
2021/01/24 14:14:28 main.go:91: Using DB: /home/tom/.local/share/gorss/gorss.db
2021/01/24 14:14:28 main.go:92: Using log file: /home/tom/.local/share/gorss/gorss.log
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x58e435]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc000160280)
	/home/nergal/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/application.go:149 +0x87
panic(0x9369a0, 0xca61f0)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.com/rivo/tview.(*Table).Draw.func1(...)
	/home/nergal/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/table.go:563
github.com/rivo/tview.(*Table).Draw(0xc0001de6e0, 0xa41fc0, 0xc0003f6000)
	/home/nergal/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/table.go:889 +0x20d5
github.com/rivo/tview.(*Flex).Draw(0xc0001f6300, 0xa41fc0, 0xc0003f6000)
	/home/nergal/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/flex.go:169 +0x2a8
github.com/rivo/tview.(*Flex).Draw(0xc0001f63f0, 0xa41fc0, 0xc0003f6000)
	/home/nergal/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/flex.go:169 +0x2a8
github.com/rivo/tview.(*Flex).Draw(0xc0001f6480, 0xa41fc0, 0xc0003f6000)
	/home/nergal/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/flex.go:173 +0x357
github.com/rivo/tview.(*Flex).Draw(0xc0001f6510, 0xa41fc0, 0xc0003f6000)
	/home/nergal/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/flex.go:173 +0x357
github.com/rivo/tview.(*Application).draw(0xc000160280, 0x0)
	/home/nergal/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/application.go:363 +0xd9
github.com/rivo/tview.(*Application).Draw.func1()
	/home/nergal/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/application.go:316 +0x2a
github.com/rivo/tview.(*Application).Run(0xc000160280, 0x0, 0x0)
	/home/nergal/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/application.go:253 +0x5a5
github.com/Lallassu/gorss/internal.(*Window).Start(0xc0001de5a0)
	/home/nergal/temp/gorss/internal/window.go:183 +0x85
github.com/Lallassu/gorss/internal.(*Controller).Init(0xc000188480, 0xc000026210, 0x22, 0xc0000262a0, 0x2c, 0xc000026330, 0x25)
	/home/nergal/temp/gorss/internal/controller.go:67 +0x3fc
main.main()
	/home/nergal/temp/gorss/cmd/gorss/main.go:101 +0x778
```

Unfortunately the log seems to be empty.
```
~ $ wc /home/tom/.local/share/gorss/gorss.log
0 0 0 /home/tom/.local/share/gorss/gorss.log
```

**Comment by danfe** [comment]
Could it be related, not sure (feel free to move to its own issue).  There seems to be some race condition when pressing "down" key shortly after seeing feed contents:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb64738]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
        github.com/rivo/tview/application.go:251 +0x4d
panic({0x2738a0, 0xc7a950})
        runtime/panic.go:884 +0x213
github.com/Lallassu/gorss/internal.(*DB).MarkRead(0x8542a5400?, 0x0)
        github.com/Lallassu/gorss/internal/db.go:189 +0xd8
github.com/Lallassu/gorss/internal.(*Window).MoveDown(0x8542a8be0, {0x3b7098?, 0x8541b1d40})
        github.com/Lallassu/gorss/internal/window.go:534 +0x1ed
github.com/Lallassu/gorss/internal.(*Controller).Input(0x8542a5400, 0x85407e0a0)
```
See the full crash log [here](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=272768#c12).
