### ISSUE TITLE
Crash from UndoLastRead if nothing previously read

### ISSUE THREAD

**Issue by dherbst** [Lallassu/gorss#28]
Encountered this crash when hitting 'u' if nothing has been read yet:

```panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x44959c1]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc000166380)
	/Users/user/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/application.go:149 +0x87
panic(0x462c100, 0x4ad9af0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/Lallassu/gorss/internal.(*Controller).Input(0xc0001ef680, 0xc0003183e0, 0xc000166380)
	/Users/user/src/d/gorss/internal/controller.go:595 +0x8e1
github.com/rivo/tview.(*Application).Run(0xc000166380, 0x0, 0x0)
	/Users/user/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/application.go:219 +0x445
github.com/Lallassu/gorss/internal.(*Window).Start(0xc000248aa0)
	/Users/user/src/d/gorss/internal/window.go:183 +0x85
github.com/Lallassu/gorss/internal.(*Controller).Init(0xc0001ef680, 0xc00014ec80, 0x37, 0x46bd878, 0x14, 0xc00014edc0, 0x35)
	/Users/user/src/d/gorss/internal/controller.go:67 +0x3fc
main.main()
	/Users/user/src/d/gorss/cmd/gorss/main.go:101 +0x778
```

**Comment by Lallassu** [comment]
Good find, and thanks for adding a fix for this!
